# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import greeter_pb2 as greeter__pb2


class GreeterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/com.example.grpc.GreeterService/SendMessage',
                request_serializer=greeter__pb2.MessageRequest.SerializeToString,
                response_deserializer=greeter__pb2.MessageResponse.FromString,
                )
        self.Transactions = channel.unary_stream(
                '/com.example.grpc.GreeterService/Transactions',
                request_serializer=greeter__pb2.TransactionRequest.SerializeToString,
                response_deserializer=greeter__pb2.TransactionResponse.FromString,
                )


class GreeterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=greeter__pb2.MessageRequest.FromString,
                    response_serializer=greeter__pb2.MessageResponse.SerializeToString,
            ),
            'Transactions': grpc.unary_stream_rpc_method_handler(
                    servicer.Transactions,
                    request_deserializer=greeter__pb2.TransactionRequest.FromString,
                    response_serializer=greeter__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.example.grpc.GreeterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GreeterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.example.grpc.GreeterService/SendMessage',
            greeter__pb2.MessageRequest.SerializeToString,
            greeter__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Transactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.example.grpc.GreeterService/Transactions',
            greeter__pb2.TransactionRequest.SerializeToString,
            greeter__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
