# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x10\x63om.example.grpc\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0fMessageResponse\x12\r\n\x05reply\x18\x01 \x01(\t\"$\n\x12TransactionRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"Q\n\x13TransactionResponse\x12\x15\n\rtransactionId\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x32\xc7\x01\n\x0eGreeterService\x12T\n\x0bSendMessage\x12 .com.example.grpc.MessageRequest\x1a!.com.example.grpc.MessageResponse\"\x00\x12_\n\x0cTransactions\x12$.com.example.grpc.TransactionRequest\x1a%.com.example.grpc.TransactionResponse\"\x00\x30\x01\x42 \n\x10\x63om.example.grpcB\x0c\x45xampleProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.example.grpcB\014ExampleProto'
  _MESSAGEREQUEST._serialized_start=35
  _MESSAGEREQUEST._serialized_end=68
  _MESSAGERESPONSE._serialized_start=70
  _MESSAGERESPONSE._serialized_end=102
  _TRANSACTIONREQUEST._serialized_start=104
  _TRANSACTIONREQUEST._serialized_end=140
  _TRANSACTIONRESPONSE._serialized_start=142
  _TRANSACTIONRESPONSE._serialized_end=223
  _GREETERSERVICE._serialized_start=226
  _GREETERSERVICE._serialized_end=425
# @@protoc_insertion_point(module_scope)
